---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_jobs.yml

# Flags specific to this branch
flags:
  post-build:
    - simulator

builds:
  android-api-15:
    platforms:
      - Android
    types:
      opt:
        task: tasks/builds/android_api_15.yml
  aries-dogfood:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_dogfood.yml
  flame-kk-ota:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_ota_opt.yml
      debug:
        task: tasks/builds/b2g_flame_kk_ota_debug.yml
  linux64-st-an:
    platforms:
      - Linux64 Static Analysis
    types:
      opt:
        task: tasks/builds/opt_linux64_st-an.yml
