---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  aries:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_opt.yml
      debug:
        task: tasks/builds/b2g_aries_spark_debug.yml
  aries-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_eng.yml
  aries-dogfood:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_dogfood.yml
        additional-parameters:
          b2g_update_channel: 'b2g-ota'
  aries-ota:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_ota_opt.yml
        additional-parameters:
          b2g_update_channel: 'b2g-ota'
      debug:
        task: tasks/builds/b2g_aries_spark_ota_debug.yml
        additional-parameters:
          b2g_update_channel: 'b2g-ota'
  flame-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_opt.yml
      debug:
        task: tasks/builds/b2g_flame_kk_debug.yml
  flame-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_eng.yml
  flame-kk-spark-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_spark_eng.yml
  flame-kk-ota:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_ota_opt.yml
        additional-parameters:
          b2g_update_channel: 'b2g-ota'
      debug:
        task: tasks/builds/b2g_flame_kk_ota_debug.yml
        additional-parameters:
          b2g_update_channel: 'b2g-ota'

tests: []
