$inherits:
  from: 'tasks/builds/firefox_l10n_base.yml'
  variables:
    build_name: 'linux64-l10n'
    platform: 'linux64'
task:
  metadata:
      name: '[TC] Linux64 L10n'
      description: 'Linux64 L10n'

  workerType: opt-linux64

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
      tier: 2
      symbol: L10n

