$inherits:
  from: 'tasks/builds/firefox_l10n_base.yml'
  variables:
    build_name: 'linux32-l10n'
    platform: 'linux32'
task:
  metadata:
      name: '[TC] Linux32 L10n'
      description: 'Linux32 L10n'

  workerType: opt-linux32

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
      tier: 2
      symbol: L10n

