$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
  variables:
    build_name: 'flame-kk'
    build_type: 'opt'
task:
  workerType: flame-kk
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-flame-kk-opt'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-flame-kk-opt-objdir-gecko'
  metadata:
    name: '[TC] B2G Flame KK Opt'

  payload:
    cache:
      level-{{level}}-{{project}}-build-flame-kk-opt: /home/worker/workspace
      level-{{level}}-{{project}}-build-flame-kk-opt-objdir-gecko: /home/worker/objdir-gecko
    env:
      TARGET: 'flame-kk'
      DEBUG: 0
    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/testing/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-phone.sh $HOME/workspace
  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      symbol: B
      groupSymbol: Flame-KK
      groupName: Flame KitKat Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'private/build/flame-kk.zip'
