$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
  variables:
    build_name: 'emulator-jb'
    build_type: 'opt'
task:
  workerType: emulator-jb
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-emulator-jb-opt'
    - 'docker-worker:cache:level-{{level}}-{{project}}-emulator-jb-opt-objdir-gecko'
  metadata:
    name: '[TC] B2G JB Emulator Opt'

  extra:
    treeherder:
      machine:
        platform: b2g-emu-jb

  payload:
    cache:
      level-{{level}}-{{project}}-emulator-jb-opt: /home/worker/workspace
      level-{{level}}-{{project}}-emulator-jb-opt-objdir-gecko: /home/worker/objdir-gecko
    env:
      TARGET: 'emulator-jb'
      TOOLTOOL_MANIFEST: 'b2g/config/emulator-jb/releng-emulator-jb.tt'
