$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
  variables:
    build_name: 'emulator-jb'
    build_type: 'debug'
task:
  workerType: emulator-jb-debug
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-emulator-jb-debug'
    - 'docker-worker:cache:level-{{level}}-{{project}}-emulator-jb-debug-objdir-gecko'
  metadata:
    name: '[TC] B2G Emulator JB Debug'

  extra:
    treeherder:
      collection:
        debug: true
      machine:
        platform: b2g-emu-jb

  payload:
    cache:
      level-{{level}}-{{project}}-emulator-jb-debug: /home/worker/workspace
      level-{{level}}-{{project}}-emulator-jb-debug-objdir-gecko: /home/worker/objdir-gecko
    env:
      TARGET: 'emulator-jb'
      B2G_DEBUG: 1
      TOOLTOOL_MANIFEST: 'b2g/config/emulator-jb/releng-emulator-jb.tt'
