$inherits:
  from: 'tasks/builds/b2g_aries_spark_ota_base.yml'
  variables:
    build_name: 'aries'
    build_type: 'opt'
task:
  metadata:
    name: '[TC] B2G Aries OTA (user)'
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-spark-ota-user'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-spark-ota-user-objdir-gecko'
  payload:
    cache:
      level-{{level}}-{{project}}-build-aries-spark-ota-user: /home/worker/workspace
      level-{{level}}-{{project}}-build-aries-spark-ota-user-objdir-gecko: /home/worker/objdir-gecko
    env:
      VARIANT: user

