$inherits:
  from: 'tasks/builds/b2g_flame_kk_ota_base.yml'
  variables:
    build_name: 'flame-kk'
    build_type: 'debug'
task:
  metadata:
    name: '[TC] B2G Flame KK OTA (userdebug)'
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-flame-kk-ota-debug'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-flame-kk-ota-debug-objdir-gecko'

  payload:
    cache:
      level-{{level}}-{{project}}-build-flame-kk-ota-debug: /home/worker/workspace
      level-{{level}}-{{project}}-build-flame-kk-ota-debug-objdir-gecko: /home/worker/objdir-gecko
    env:
      VARIANT: userdebug
      B2G_DEBUG: 0
