$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
  variables:
    build_type: 'opt'
    build_name: 'emulator-ics'
task:
  workerType: emulator-ics
  routes:
    - 'index.buildbot.branches.{{project}}.emulator-ics'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.emulator-ics'
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-emulator-ics-opt'
    - 'docker-worker:cache:level-{{level}}-{{project}}-emulator-ics-opt-objdir-gecko'
  metadata:
    name: '[TC] B2G Emulator ICS Opt'

  extra:
    treeherder:
      machine:
        platform: b2g-emu-ics

  payload:
    cache:
      level-{{level}}-{{project}}-emulator-ics-opt: /home/worker/workspace
      level-{{level}}-{{project}}-emulator-ics-opt-objdir-gecko: /home/worker/objdir-gecko

    env:
      TARGET: 'emulator'
      TOOLTOOL_MANIFEST: 'b2g/config/emulator-ics/releng-emulator-ics.tt'
