$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
  variables:
    build_name: 'emulator-kk'
    build_type: 'debug'
task:
  workerType: emulator-kk-debug
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-emulator-kk-debug'
    - 'docker-worker:cache:level-{{level}}-{{project}}-emulator-kk-debug-objdir-gecko'
  metadata:
    name: '[TC] B2G Emulator KK Debug'

  extra:
    treeherder:
      collection:
        debug: true
      machine:
        platform: b2g-emu-kk

  payload:
    cache:
      level-{{level}}-{{project}}-emulator-kk-debug: /home/worker/workspace
      level-{{level}}-{{project}}-emulator-kk-debug-objdir-gecko: /home/worker/objdir-gecko
    env:
      TARGET: 'emulator-kk'
      TOOLTOOL_MANIFEST: 'b2g/config/emulator-kk/releng-emulator-kk.tt'
      B2G_DEBUG: 1
