$inherits:
  from: 'tasks/build.yml'
  variables:
    build_product: 'b2g'
task:
  payload:
    image:
      type: 'task-image'
      path: 'public/image.tar'
      taskId: '{{#task_id_for_image}}builder{{/task_id_for_image}}'
  extra:
    locations:
      test_packages: 'public/build/test_packages.json'
      mozharness: 'public/build/mozharness.zip'
