$inherits:
  from: 'tasks/builds/b2g_flame_kk_ota_base.yml'
  variables:
    build_name: 'flame-kk'
    build_type: 'opt'
task:
  metadata:
    name: '[TC] B2G Flame KK OTA (user)'
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-flame-kk-ota-user'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-flame-kk-ota-user-objdir-gecko'

  payload:
    cache:
      level-{{level}}-{{project}}-build-flame-kk-ota-user: /home/worker/workspace
      level-{{level}}-{{project}}-build-flame-kk-ota-user-objdir-gecko: /home/worker/objdir-gecko
    env:
      VARIANT: user
