$inherits:
  from: 'tasks/builds/b2g_aries_spark_ota_base.yml'
  variables:
    build_name: 'aries'
    build_type: 'debug'
task:
  metadata:
    name: '[TC] B2G Aries OTA (userdebug)'
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-spark-ota-debug'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-spark-ota-debug-objdir-gecko'
  payload:
    cache:
      level-{{level}}-{{project}}-build-aries-spark-ota-debug: /home/worker/workspace
      level-{{level}}-{{project}}-build-aries-spark-ota-debug-objdir-gecko: /home/worker/objdir-gecko
    env:
      VARIANT: userdebug
      B2G_DEBUG: 0

