$inherits:
  from: 'tasks/builds/b2g_aries_spark_ota_base.yml'
  variables:
    build_name: 'aries-dogfood'
    build_type: 'debug'
task:
  metadata:
    name: '[TC] B2G Aries Dogfood'
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-spark-dogfood'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-spark-dogfood-objdir-gecko'
  payload:
    cache:
      level-{{level}}-{{project}}-build-aries-spark-dogfood: /home/worker/workspace
      level-{{level}}-{{project}}-build-aries-spark-dogfood-objdir-gecko: /home/worker/objdir-gecko
    env:
      VARIANT: userdebug
      DOGFOOD: 1
      MOZHARNESS_CONFIG: b2g/taskcluster-spark-dogfood.py
      B2G_UPDATE_CHANNEL: '{{b2g_update_channel}}'
  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      symbol: B
      groupSymbol: Aries-DogFood
      groupName: Aries Device Image
      machine:
        platform: b2g-device-image
      collection:
        debug: true
