$inherits:
  from: 'tasks/builds/firefox_base.yml'
  variables:
    build_name: 'linux32'
task:
  #workerType: ..

  routes:
    - 'index.buildbot.branches.{{project}}.linux32'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.linux32'

  scopes:
    - 'docker-worker:cache:tooltool-cache'
    - 'docker-worker:relengapi-proxy:tooltool.download.public'

  payload:
    cache:
      # "clobber" means no workspace cache; non-clobber subclasses should add that
      tooltool-cache: '/home/worker/tooltool-cache'

    features:
      relengAPIProxy: true

    env:
      MOZHARNESS_SCRIPT: 'mozharness/scripts/fx_desktop_build.py'
      MOZHARNESS_CONFIG: 'builds/releng_base_linux_32_builds.py balrog/production.py'
      MH_BRANCH: {{project}}
      MH_BUILD_POOL: taskcluster
      # image paths
      TOOLTOOL_CACHE: '/home/worker/tooltool-cache'
      NEED_XVFB: true

    maxRunTime: 36000

    command: ["/bin/bash", "bin/build.sh"]

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      machine:
        # see https://github.com/mozilla/treeherder/blob/master/ui/js/values.js
        platform: linux32
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located, relative to the task's artifacts URL
    locations:
      build: 'public/build/target.tar.bz2'
      tests: 'public/build/target.tests.zip'
