$inherits:
  from: 'tasks/build.yml'
  variables:
    build_product: 'mobile'
task:
  payload:
    image:
      type: 'task-image'
      path: 'public/image.tar'
      taskId: '{{#task_id_for_image}}desktop-build{{/task_id_for_image}}'

