[package]
name = "mp4parse"
version = "0.4.0"
authors = [
  "Ralph Giles <giles@mozilla.com>",
  "Matthew Gregan <kinetik@flim.org>",
]

description = "Parser for ISO base media file format (mp4)"
license = "MPL-2.0"

repository = "https://github.com/mozilla/mp4parse-rust"

# Cargo includes random files from the working directory
# by default! Avoid bloating the package with test files.
exclude = [
  "*.mp4",
]

build = "build.rs"

[dependencies]
byteorder = "0.5.0"
afl = { version = "0.1.1", optional = true }
afl-plugin = { version = "0.1.1", optional = true }
abort_on_panic = { version = "1.0.0", optional = true }

[dev-dependencies]
test-assembler = "0.1.2"

[build-dependencies]
rusty-cheddar = "0.3.2"

[features]
fuzz = ["afl", "afl-plugin", "abort_on_panic"]

# Somewhat heavy-handed, but we want at least -Z force-overflow-checks=on.
[profile.release]
debug-assertions = true
