[package]
name = "mp4parse"
version = "0.4.0"
authors = [
  "Ralph Giles <giles@mozilla.com>",
  "Matthew Gregan <kinetik@flim.org>",
]

description = "Parser for ISO base media file format (mp4)"
license = "MPL-2.0"

repository = "https://github.com/mozilla/mp4parse-rust"

# Cargo includes random files from the working directory
# by default! Avoid bloating the package with test files.
exclude = [
  "*.mp4",
]

# Somewhat heavy-handed, but we want at least -Z force-overflow-checks=on.
[profile.release]
debug-assertions = true

[dependencies]
byteorder = { path = "../byteorder" }
