/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */
// Enable webm by default to enable playback of youtube/vimio/vevo etc.
pref("media.mediasource.enabled", true);
pref("media.mediasource.webm.enabled", true);
pref("media.mediasource.format-reader", false);
pref("media.mediasource.mp4.enabled", true);
// Enable skipping loop filter and allow non spec compliant speedup tricks.
pref("media.ffmpeg.skip_loop_filter", true);
