# This task is the base for most tests in gecko.
task:
  created: '{{now}}'
  deadline: '{{#from_now}}24 hours{{/from_now}}'
  metadata:
    source: '{{source}}'
    owner: mozilla-taskcluster-maintenance@mozilla.com
  tags:
    createdForUser: {{owner}}
  workerType: b2gtest
  provisionerId: aws-provisioner-v1
  schedulerId: task-graph-scheduler

  scopes:
    - 'docker-worker:image:{{#docker_image}}tester-device{{/docker_image}}'
    - 'queue:create-task:aws-provisioner-v1/testdroid-device'
    - 'docker-worker:cache:level-{{level}}-{{project}}-tc-vcs'
    - 'docker-worker:capability:device:phone'

  payload:
    image: '{{#docker_image}}tester-device{{/docker_image}}'
    maxRunTime: 3600
    cache:
      level-{{level}}-{{project}}-tc-vcs: '/home/worker/.tc-vcs'
    env:
      GAIA_HEAD_REPOSITORY: '{{{gaia_head_repository}}}'
      GAIA_BASE_REPOSITORY: '{{{gaia_base_repository}}}'
      GAIA_REF: '{{{gaia_ref}}}'
      GAIA_REV: '{{{gaia_rev}}}'

    # All builds share a common artifact directory for ease of uploading.
    artifacts:
      'private/logs':
        type: directory
        path: '/home/worker/upload/logs/'
        expires: '{{#from_now}}1 year{{/from_now}}'

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
    chunks:
      total: 1
      current: {{chunk}}
